export interface Recipe {
  id: number;
  title: string;
  date: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  marginNote: string;
  ingredients: string[];
  instructions: string[];
  bottomNote: string;
  category?: string;
  thumbnail?: string;
  author?: string;
  likes?: number;
}

export const recipes: Recipe[] = [
  {
    id: 1,
    title: "Tarte aux Pommes de Grand-Mere",
    date: "Septembre 1987",
    prepTime: "30 min",
    cookTime: "45 min",
    servings: 8,
    marginNote: "Le secret c'est le beurre sale !",
    category: "Dessert",
    thumbnail: "/apple-tart-french-dessert.jpg",
    author: "@mamie_cuisine",
    likes: 2340,
    ingredients: [
      "250g de farine",
      "125g de beurre froid",
      "1 pincee de sel",
      "5 pommes Golden",
      "100g de sucre",
      "1 sachet de sucre vanille",
      "Cannelle (facultatif)",
    ],
    instructions: [
      "Preparer la pate : melanger la farine et le sel, ajouter le beurre en morceaux et sabler du bout des doigts.",
      "Ajouter un peu d'eau froide pour former une boule. Laisser reposer 30 min au frais.",
      "Eplucher et couper les pommes en fines lamelles.",
      "Etaler la pate dans un moule beurre, disposer les pommes en rosace.",
      "Saupoudrer de sucre et de cannelle. Parsemer de noisettes de beurre.",
      "Enfourner a 180 C pendant 45 minutes jusqu'a ce que les bords soient dores.",
    ],
    bottomNote: "Recette de Mamie Jeanne - a faire les dimanches d'automne",
  },
  {
    id: 2,
    title: "Blanquette de Veau",
    date: "Hiver 1992",
    prepTime: "45 min",
    cookTime: "1h30",
    servings: 6,
    marginNote: "Toujours avec du riz !",
    category: "Plat",
    thumbnail: "/blanquette-veau-french-stew-cream.jpg",
    author: "@chef_traditionnel",
    likes: 1856,
    ingredients: [
      "1kg de veau (epaule)",
      "2 carottes",
      "2 poireaux",
      "1 oignon pique de clous de girofle",
      "1 bouquet garni",
      "200g de champignons",
      "30cl de creme fraiche",
      "2 jaunes d'oeufs",
    ],
    instructions: [
      "Mettre la viande dans une grande cocotte, couvrir d'eau froide. Porter a ebullition et ecumer.",
      "Ajouter les legumes, le bouquet garni et l'oignon. Saler. Cuire 1h30 a feu doux.",
      "Retirer la viande et les legumes. Filtrer le bouillon.",
      "Faire revenir les champignons dans du beurre.",
      "Preparer la sauce : melanger creme et jaunes d'oeufs, incorporer le bouillon chaud en fouettant.",
      "Napper la viande de sauce cremeuse. Servir aussitot !",
    ],
    bottomNote: "Le plat prefere de Papa - ne pas oublier le persil frais",
  },
  {
    id: 3,
    title: "Ramen Tonkotsu Maison",
    date: "2024",
    prepTime: "1h",
    cookTime: "12h",
    servings: 4,
    marginNote: "Patience is key!",
    category: "Asiatique",
    thumbnail: "/ramen-tonkotsu-japanese-noodles-pork.jpg",
    author: "@ramen_lover",
    likes: 5420,
    ingredients: [
      "Os de porc 1kg",
      "Nouilles ramen fraiches",
      "4 oeufs mollets",
      "Chashu porc",
      "Nori",
      "Oignons verts",
    ],
    instructions: [
      "Blanchir les os de porc 10 min.",
      "Cuire a feu vif pendant 12h en ajoutant de l'eau.",
      "Filtrer le bouillon cremeux.",
      "Assembler avec les garnitures.",
    ],
    bottomNote: "Le secret c'est le temps de cuisson",
  },
  {
    id: 4,
    title: "Tacos Al Pastor",
    date: "2024",
    prepTime: "30 min",
    cookTime: "2h",
    servings: 6,
    marginNote: "Marinade overnight!",
    category: "Mexicain",
    thumbnail: "/tacos-al-pastor-mexican-pineapple.jpg",
    author: "@taco_master",
    likes: 3210,
    ingredients: [
      "1kg d'epaule de porc",
      "Piments guajillo",
      "Ananas frais",
      "Tortillas de mais",
      "Coriandre",
      "Oignon blanc",
    ],
    instructions: [
      "Preparer la marinade avec les piments.",
      "Mariner le porc toute la nuit.",
      "Cuire lentement au four.",
      "Servir avec ananas grille.",
    ],
    bottomNote: "Authentique recette de Mexico City",
  },
  {
    id: 5,
    title: "Pasta Carbonara",
    date: "2024",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    marginNote: "No cream ever!",
    category: "Italien",
    thumbnail: "/pasta-carbonara-italian-guanciale-egg.jpg",
    author: "@pasta_queen",
    likes: 8932,
    ingredients: [
      "400g spaghetti",
      "200g guanciale",
      "4 jaunes d'oeufs",
      "100g pecorino romano",
      "Poivre noir",
    ],
    instructions: [
      "Cuire les pates al dente.",
      "Faire rissoler le guanciale.",
      "Melanger oeufs et fromage.",
      "Emulsionner hors du feu.",
    ],
    bottomNote: "La vraie recette romaine",
  },
  {
    id: 6,
    title: "Pad Thai",
    date: "2024",
    prepTime: "20 min",
    cookTime: "10 min",
    servings: 2,
    marginNote: "Wok tres chaud!",
    category: "Asiatique",
    thumbnail: "/pad-thai-noodles-shrimp-peanuts-thai.jpg",
    author: "@bangkok_street",
    likes: 4521,
    ingredients: [
      "200g nouilles de riz",
      "200g crevettes",
      "2 oeufs",
      "Sauce tamarin",
      "Cacahuetes",
      "Germes de soja",
    ],
    instructions: [
      "Tremper les nouilles.",
      "Sauter les crevettes.",
      "Ajouter oeufs et nouilles.",
      "Assaisonner et garnir.",
    ],
    bottomNote: "Street food de Bangkok",
  },
  {
    id: 7,
    title: "Croissants Maison",
    date: "2024",
    prepTime: "4h",
    cookTime: "20 min",
    servings: 12,
    marginNote: "Beurre tres froid!",
    category: "Boulangerie",
    thumbnail: "/croissants-french-pastry-butter-golden.jpg",
    author: "@boulanger_paris",
    likes: 6743,
    ingredients: [
      "500g farine T45",
      "280g beurre",
      "10g sel",
      "80g sucre",
      "10g levure",
      "300ml lait",
    ],
    instructions: [
      "Preparer la detrempe.",
      "Incorporer le beurre en tourage.",
      "3 tours simples.",
      "Faconner et cuire.",
    ],
    bottomNote: "Comme a la boulangerie",
  },
  {
    id: 8,
    title: "Pho Bo Vietnamien",
    date: "2024",
    prepTime: "30 min",
    cookTime: "6h",
    servings: 6,
    marginNote: "Bouillon clair!",
    category: "Asiatique",
    thumbnail: "/pho-bo-vietnamese-beef-noodle-soup.jpg",
    author: "@hanoi_kitchen",
    likes: 3890,
    ingredients: [
      "Os de boeuf 2kg",
      "Boeuf tranche fin",
      "Nouilles de riz",
      "Anis etoile",
      "Cannelle",
      "Herbes fraiches",
    ],
    instructions: [
      "Rotir les os au four.",
      "Mijoter 6h avec epices.",
      "Clarifier le bouillon.",
      "Assembler les bols.",
    ],
    bottomNote: "Recette de famille de Hanoi",
  },
  {
    id: 9,
    title: "Tiramisu Classique",
    date: "2024",
    prepTime: "30 min",
    cookTime: "0 min",
    servings: 8,
    marginNote: "Repos 24h minimum!",
    category: "Dessert",
    thumbnail: "/tiramisu-italian-dessert-coffee-mascarpone.jpg",
    author: "@dolce_vita",
    likes: 7234,
    ingredients: [
      "500g mascarpone",
      "4 oeufs",
      "100g sucre",
      "Cafe espresso",
      "Biscuits savoiardi",
      "Cacao amer",
    ],
    instructions: [
      "Preparer la creme au mascarpone.",
      "Tremper les biscuits.",
      "Monter en couches.",
      "Refrigerer 24h.",
    ],
    bottomNote: "Le dessert italien par excellence",
  },
  {
    id: 10,
    title: "Butter Chicken",
    date: "2024",
    prepTime: "20 min",
    cookTime: "40 min",
    servings: 4,
    marginNote: "Marinade importante!",
    category: "Indien",
    thumbnail: "/butter-chicken-indian-curry-naan.jpg",
    author: "@delhi_spices",
    likes: 5123,
    ingredients: [
      "800g poulet",
      "Yaourt grec",
      "Garam masala",
      "Tomates",
      "Creme fraiche",
      "Beurre",
    ],
    instructions: [
      "Mariner le poulet.",
      "Griller au four.",
      "Preparer la sauce.",
      "Mijoter ensemble.",
    ],
    bottomNote: "Cremeux et parfume",
  },
];
